@token = eyJraWQiOiJXY0FQdnJieV9XMkl0dmJnbHJQVDJMbmFTbEt2Y0tRdnJGWXVnb1hhSFlRIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJ0YXBwZWQtYmFja2VuZCIsInN1YiI6ImFkNjE3OGJlLWU1ZjYtNGM2MS04MjI4LWUyYzAyNWQzNjBjZiIsInJvbGUiOiJVU0VSIiwiZXhwIjoxNzg3NTcwNDc5LCJpYXQiOjE3ODc1NjY4Nzl9.mNtOw24jC1orvComZRiLk7Hg4zMZWNL3sabBHJABEegtDsF4YIDUOaJuBfiNy_FiaYCjQhNWo-w4YhYVSWKed3xUtI3pgXKjrvV9_3JrX72UEtcOAIfZAzxqOsfzDkEhS9lUTG-rfpqmxCl371UYUGVWQYm5WFa4SbAA5rwq88xSkNM07a_bW3dQ3V0HXlcvAAFruTjwK4AMVHVWx2FSubP-ODW4h69_1dyFop7jutfaN80EnJfcUbAQRrwScvf6c4qLi1d1cc6IH3odppglhGy1amC-gczE-pAp-pDkDXNK5qMyumKWHsUsthheTK7JIctvmAjJpa1uFBxHFHm8mw

GET http://localhost:8080/test/jwt
Authorization: Bearer {{token}}

