  spring:

    config:
      import: "optional:file:.env[.properties]"

    application:
      name: backend

    datasource:
      url: jdbc:postgresql://localhost:5432/tapped
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}

    jpa:
      open-in-view: false
      hibernate:
        ddl-auto: validate

    flyway:
      enabled: true

    security:
      oauth2:
        client:
          registration:
            google:
              client-id: ${GOOGLE_CLIENT_ID}
              client-secret: ${GOOGLE_CLIENT_SECRET}
              scope:
                - openid
                - profile
                - email
    jwt:
        public-key: classpath:keys/public.pem
        private-key: file:${JWT_PRIVATE_KEY_PATH}

    resend:
      api-key: ${RESEND_API_KEY}
      from-address: ${MAIL_FROM_ADDRESS:no-reply@notify.goofed.co}
      subject-prefix: ${MAIL_SUBJECT_PREFIX:Goofed}

    app:
      base-url: ${APP_BASE_URL:http://localhost:3000}