package games.tapped.play.entity;

public enum ChallengeEventType {
    MAIL_SENT,
    MAIL_FAILED,
    MAIL_TOKEN_CREATED,
    REF_DECISION_SUCCESS,
    REF_DECISION_FAIL,
    REF_DECISION_DISAGREE,
    MAIL_TOKEN_CREATED_FAILED,
    CHALLENGER_FINALIZED_SUCCESS,
    CHALLENGER_FINALIZED_FAIL,
    CHALLENGER_FINALIZED_CHICKEN,
    CHALLENGER_FINALIZED_DISAGREE
}
